baseURL = 'https://hugo-landrin.fr'
languageCode = 'fr-fr'
title = 'Hugo Landrin'
theme = 'PaperMod'
enableEmoji = true

[params]
env = 'production'
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = 'Hugo Landrin'

[params.homeInfoParams]
Title = "Bienvenue"
Content = "Site de Hugo Landrin"

defaultTheme = 'auto'
# disableThemeToggle = true
ShowShareButtons = true
ShowReadingTime = true
# disableSpecial1stPost = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true